getStatusCode() support
robertfausk/mink-panther-driver pull request #13
Opened 2020-02-25 13:09 UTC by dkarlovi

Adds support for Mink's `getStatusCode()`

2020-02-25 13:16 UTC, dkarlovi commented
Build failures unrelated, don't know what's that about.

2020-03-28 18:14 UTC, robertfausk requested changes
This library currently does not have fully support for symfony/panther with HttpBrowserClient atm.
It's unlikely that I find time to add tested support for HttpBrowserClient in the near future but PRs are always welcome!:)

We also need some tests for different status codes.

2020-03-28 18:14 UTC, robertfausk commented on src/PantherDriver.php
> +    private const FIREFOX = 'firefox';
You can remove these lines. They are already merged and not relevant to this PR.

2020-03-28 18:18 UTC, robertfausk commented on src/PantherDriver.php
> +        return $this->client->getInternalResponse()->getStatusCode();
Here we need to distinguish between the types of the client: PantherClient and HttpBrowserClient
The code would be similar to the following:
```PHP
public function getStatusCode()
{
    if ($this->client instanceof HttpBrowserClient) {
        return $this->client->getInternalResponse()->getStatusCode();
    }
    throw new UnsupportedDriverActionException('Status code is not available from "%s" with client of type "%s"', $this, \get_class($this->client));
}
```

2020-11-26 09:16 UTC, closed without merging